version: '3.4'

services:
  restorix:
    image: ${DOCKER_REGISTRY-}restorix
    build:
      context: .
      dockerfile: Restorix/Dockerfile
    ports:
      - 5050:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: restorix_db
      POSTGRES_USER: restorix_user
      POSTGRES_PASSWORD: restorix_password
    volumes:
      - postgres-restorix-data:/var/lib/postgresql/data
    ports:
      - 5052:5432

volumes:
  postgres-restorix-data: